version: '3'

services:
  test_app:
    container_name: "test_app"
    build:
      dockerfile: Deploy/Docker/Dockerfile
      context: ../../.
    ports:
      - "8080:80"
      - "50051:50051"
    env_file:
      - ../../.env
    networks:
      - backend

networks:
  backend:
    driver: bridge
